# Generated by Django 4.0.5 on 2022-06-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/shop/noPhoto.png', upload_to=''),
        ),
    ]
