# Generated by Django 4.0.5 on 2022-06-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='shop/static/shop/noPhoto.png', upload_to=''),
        ),
    ]
