# Generated by Django 4.0.5 on 2022-06-20 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
